name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t jargoh999/project_mgt:latest .

      - name: Push Docker image to  Hub
        run: docker push jargoh999/project_mgt:latest

      - name: Deploy to AWS EC2
        env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          AWS_HOST: ${{ secrets.AWS_HOST }}
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.AWS_HOST }} << 'EOF'
            # Cleanup existing containers and images
            sudo docker container prune -f
            sudo docker image prune -f
            
            # Remove specific container if it exists
            sudo docker rm -f project_mgt || true
            
            # Pull the latest image
            sudo docker pull jargoh999/project_mgt:latest
            
            # Run the new container
            sudo docker run -d --name project_mgt -p 8000:8000 jargoh999/project_mgt:latest
          EOF